### PR TITLE
add jruby to travis

### LINKED ISSUE #53: test against latest jruby
update .travis.yml

### PR DESCRIPTION
**Pull request by gregmolnar**
closes #53

### CODE REVIEW

**Comment by smudge** [comment]
Hmm -- Travis failed to install jruby. Try specifying a version, like `jruby-9.1.9.0`.

**Comment by smudge** [comment]
Oh I see -- yeah the pg database adapter is MRI-only too. You'll need to use `activerecord-jdbcpostgresql-adapter` on jruby.

**Comment by samandmoore** [comment]
Perhaps, it's not worth it for us to get this app deployable via JRuby. I added the issue because it seemed nice to enable folks to deploy this as a JRuby app if they so desired, but I'm not sure that we want to commit to maintaining JRuby support for this application. 

Given that, and the small, but not insignificant, trouble of getting JRuby support, I'm going to close this PR.

Thanks a lot to @gregmolnar for diving into this issue. I'm sorry for the unsatisfying result. I hope that you're still interested in getting involved in the project, if so, check out some more of issues on GitHub.

**Comment by gregmolnar** [comment]
No worries. I agree, there might be other compatibility issues as well with jruby so it probably doesn't worth the effort.

**Pull request closed without merging**
