### PR TITLE
Refactor Variant Detail presentation

### PR DESCRIPTION
**Pull request by agirlnamedsophia**
* Split presenter goes away and VariantDetail handles view related details
* This resolves a problem with the `test_track_rails_client` where we were leaning on updated records to display variant_detail `display_name`s, though on the server we were lazily initializing them. The client would only display `variant_details` that had been updated, so unless the data was updated manually the rows would be empty.

/domain @Betterment/test_track_core @dschaub

### CODE REVIEW

**Comment by dschaub** [comment]
i thought there was a split presenter, or maybe variant presenter, spec that would need to be deleted?

**Comment by agirlnamedsophia** [comment]
@dschaub  you were right! i deleted them

**Comment by dschaub** [comment]
we probably want those specs in variant_detail_spec now

**Comment by agirlnamedsophia** [comment]
bump @dschaub

**Comment by dschaub** [comment]
<< domain lgtm

**Pull request merged**
