### PR TITLE
Upgrade to Rails 5.2.

### PR DESCRIPTION
**Pull request by temochka**
### Summary

I upgraded test_track to Rails 5.2.

### Other Information

All automated tests seem to pass locally and I was able to log in without a problem. Any others tests we should perform?

/domain @Betterment/test_track_core

### CODE REVIEW

**Comment by aburgel** [comment]
<< domainlgtm

we should test out a deploy against a non-prod environment, and if that looks good then :shipit:

**Comment by smudge** [comment]
platform LGTM!

**Comment by temochka** [comment]
nanda?

**Comment by temochka** [comment]
@smudge << platform

**Pull request merged**
